title: "Yll棒"
author: "杨柳"
email: "2630533966@qq.com"
description: >- 
  在这里记录科研探索、代码日常，以及每一次马拉松与山野徒步的风景。
theme: minima

# 在页脚生成社交图标
social_links:
  github: liu-yang1

# 顶部导航栏显示的页面
header_pages:
  - about.md
  - Reading.md
  - Links.md
